export class Person {
  firstName: string;
  lastName: string;
  middleName?: string;
  gender?: string;
}

export class Task {
  id: string;
  description: string;
  isComplete: boolean;
  time?: string;

  constructor(description: string, isComplete: boolean = false) {
    this.description = description;
    this.isComplete = isComplete;
    
  }

}

export class Resident extends Person {
  id?: string;
  birthDate?: string;
  ssn?: string;
  gender?: string;
  code?: string;
  isAmbulatory?: boolean;
  isVerbal?: boolean;
  religion?: string;
  profileUrl?: string;
  medications?: MedicationRecord[] | number;
  weightLog?: Object[];
  emergencyContacts?: Object[];
  facilityInfo?: Object;
  paymentInfo?: Object
  
}

export class PrnRecord {
  id?: string;
  medication: MedicationRecord;
  reasonGiven: string;
  givenAt: string;
  givenBy: Employee;
  followUpDateTime: string;
  response?: string;
  responseNotes?: string;
}

export class Medication {
  brandName: string;
  genericName: string;
  description?: string;
  strength?: {amount: number; measurement: string;};
  form?: string;
  imageUrl?: string;
}

export class MedicationRecord extends Medication {
  id?: string
  instructions?: string;
  status?: string;
  statusHistory?: MedicationStatusHistory[];
  history?: MedicationHistoryRecord[];
  startDate?: string;
  endDate?: string;
  createDate?: string; // should be autogenerated on the date the medication record was createDate
  createdBy?: User; // the user that created the medication record
  dosage?: Dosage;
  startQuantity?: number;
  quantity?: number;
}
export class MedicationHistoryRecord {
  action: string;
  actionDate: Date;
  user: User;

}

export class MedicationStatusHistory {
  status: string;
  date: Date;
  restartDate?: Date;
  changeDate?: Date;
}

export class MedicationPrescription {
  id?: string;
  resident: Resident;
  prescriber: Specialist;
  medication: Medication;
  dosage: Dosage;
  routeOfAdministration
  schedule
  instructions
}

export class Dosage {
  amount: number; // amount of a drug taken at any one time
  measurement?: string;
  form?: string // 

}

export class Specialist {

}

export class Employee extends Person {
  id?: string;
  birthDate?: Date;
  profileUrl?: string;
  hireDate?: Date;
  terminationDate?: Date;
  ssn?: string;

}

export class Permission {
  id: string;
  title: string;
  code: string
}

export class User {
  id?: string;
  firstName: string;
  lastName: string;
  permissions?: Permission[];
  notifications?: Notification[]
}

export class Notification {
  id?: string;
  type: string;
  source: string;
  event: string;
  dismissed: boolean;
  data: Object;
}

